version: "3.0"
services:
  gnocchi:
    build: 
      context: ./gnochi
      dockerfile: ../Dockerfile
    env_file:
      - .env
    environment:
      KAFKA_TOPIC: gnocchi
    restart: always

  netdata:
    extends: gnocchi
    build: 
      context: ./netdata
    environment:
      KAFKA_TOPIC: netdata

  prometheus:
    extends: gnocchi
    build: 
      context: ./node_exporter
    environment:
      KAFKA_TOPIC: prometheus

  telegraf:
    extends: gnocchi
    build: 
      context: ./telegraf
    environment:
      KAFKA_TOPIC: telegraf
      
  esight_if:
    extends: gnocchi
    build: 
      context: ./eSight_interfaces
    environment:
      KAFKA_TOPIC: esight_interface
      
  esight_slots:
    extends: gnocchi
    build: 
      context: ./eSight_routers
    environment:
      KAFKA_TOPIC: esight_slot

  perfsonar:
    extends: gnocchi
    build: 
      context: ./perfsonar
    environment:
      KAFKA_TOPIC: perf
